### ISSUE TITLE
Missing Functionality in the Docs

### ISSUE THREAD

**Issue by 360disrupt** [scribbletune/scribbletune.com#6]
I think there are still some functions/props missing in the documentation. I didn't find docs for:

- accentMap
- sizzle

which you show in the YouTube talk ([sizzle](https://youtu.be/iwuZzp_ZnLo?t=902) & [accentMap](https://youtu.be/iwuZzp_ZnLo?t=1331) )

**Comment by walmik** [comment]
Hi @360disrupt Thank you for highlighting the missing documentation. I ll add this around next week and update here again.

**Comment by walmik** [comment]
I ve added the missing documentation @360disrupt
I ve renamed accentMap to accent and also introduced some improvements to sizzle and accent. Also just released a new version v3.0.0... do lemme know if you see anything else missing :)
